// ============================================================================
// tau_soc_tb.v — testbench for the Tau SoC: a real RV32I program runs on PicoRV32
// and drives all four ternary subsystems through their memory-mapped peripherals:
//   TGRAD/TRECON/TRELAX field accelerator (0x2000) + ternary transport link (0x3000).
//
// Program (rtl/program_tau.hex, generated by scripts/gen_program_tau.py):
//   * TGRAD  : field F0=+3 (cell 20), F1=+9 (cell 8), center=6 -> div=+3, curl=+9
//   * TRECON : gauge-fixed ∇⁻¹ store; round trip -> F0'=+3, F1'=+9, ofit=0
//   * TRELAX : one heat step -> center cell 6 = +1  (sum/9 = 12/9 = 1)
//   * LINK   : all-null word -> 12 nulls, 60 centi-pJ; 0x010 -> 11 nulls, 175 centi-pJ
// ============================================================================
`timescale 1ns/1ps

module tau_soc_tb;

  reg clk, resetn;
  wire trap;
  tau_soc u_soc (.clk(clk), .resetn(resetn), .trap(trap));

  integer i, errors;

  // decode an 8-trit balanced-ternary word (2 bits/trit) back to a signed integer
  function integer tdec;
    input [15:0] f;
    integer j, pv;
    begin
      tdec = 0; pv = 1;
      for (j = 0; j < 8; j = j + 1) begin
        case (f[j*2 +: 2])
          2'b01: tdec = tdec + pv;
          2'b10: tdec = tdec - pv;
        endcase
        pv = pv * 3;
      end
    end
  endfunction

  // assert helper
  task chk;
    input integer actual, expected;
    input [80*8:1] msg;
    begin
      if (actual !== expected) begin
        errors = errors + 1;
        $display("  FAIL %0s: got %0d, expect %0d", msg, actual, expected);
      end else
        $display("  ok   %0s = %0d", msg, actual);
    end
  endtask

  always #5 clk = ~clk;

  initial begin
    clk = 0; resetn = 0; errors = 0;
    repeat (2) @(posedge clk);
    resetn = 1;

    for (i = 0; i < 800; i = i + 1) @(posedge clk);

    $display("Tau SoC — PicoRV32 + hex MMU + field accel (TGRAD/TRECON/TRELAX) + ternary link");
    chk(tdec(u_soc.memory[8][15:0]),  3,  "TGRAD div");
    chk(tdec(u_soc.memory[9][15:0]),  9,  "TGRAD curl");
    chk(tdec(u_soc.memory[10][15:0]), 3,  "TRECON F0' (round trip)");
    chk(tdec(u_soc.memory[11][15:0]), 9,  "TRECON F1' (round trip)");
    chk(u_soc.memory[12],             0,  "TRECON overflow flag");
    chk(tdec(u_soc.memory[13][15:0]), 1,  "TRELAX center' (= sum/9 = 12/9)");
    chk(u_soc.memory[14],            12,  "link null count (all-null word)");
    chk(u_soc.memory[15],            60,  "link energy centi-pJ (all-null)");
    chk(u_soc.memory[16],            11,  "link null count (0x010 word)");
    chk(u_soc.memory[17],           175,  "link energy centi-pJ (0x010)");

    if (errors == 0)
      $display("PASS — the full processor ran TGRAD + TRECON + TRELAX + ternary transport.");
    else
      $display("FAIL — %0d assertion(s) failed", errors);
    $finish;
  end

endmodule
