import Lake
open Lake DSL

-- Reference lakefile (the authoritative one is generated by `lake new hexagon math`;
-- see SETUP.md). `lean_lib Hexagon` means modules are named Hexagon.*
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git"

lean_lib Hexagon
