#!/usr/bin/env python3
"""Generate ternary_sweep.cir — full lever sweep of the AC-polarity ternary cell.

Levers:
  diode model : DIDEAL (IS=1e-14) vs DSCHOTTKY (IS=1e-9, Vf~0.35V)
  IP          : 0.2m, 0.5m, 1m        (pulse amplitude, A)
  PW          : 0.5n, 1n, 3n, 10n     (pulse width, s)
  RW          : 100, 500              (wire R, ohm)
  CLINE       : 0.5p, 1p              (wire C, F)

Grid = 2*3*4*2*2 = 96 instances, each a self-contained 4-case cell
(push / pull / push->pull cycle), measured with its own .meas set.
Rise/fall of the current pulse = PW/5 (trapezoid stays 60% flat top).
"""
from itertools import product

IPS   = [("02", "0.2m"), ("05", "0.5m"), ("10", "1m")]
PWS   = [("05", "0.5n"), ("10", "1n"), ("30", "3n"), ("100", "10n")]
RWS   = [("100", "100"), ("500", "500")]
CLS   = [("05", "0.5p"), ("10", "1p")]
MODS  = [("ID", "ternary_case", "DIDEAL"), ("SC", "ternary_case_s", "DSCHOTTKY")]

# windows are fixed literals: each window is wider than the longest pulse
# (PW=10n -> pulse 100..114n etc.); after a pulse the driver current is 0 so
# extra window length adds nothing to the integral.
W_PUSH = "FROM=9n TO=26n"
W_PULL = "FROM=39n TO=56n"
W_CYC1 = "FROM=99n TO=123n"
W_CYC2 = "FROM=123n TO=139n"
W_CYCT = "FROM=99n TO=139n"

def subckt(name, dmod):
    return f"""\
.subckt {name} vss ip=1m pw=3n rw=500 cl=1p
* ---- push (+1): 1mA pulse into the wire at 10..~14n ----
IpA 0 dA PULSE(0 {{ip}} 10n {{pw/5}} {{pw/5}} {{pw}} 200n)
VsA dA drvA DC 0
RwA drvA xA {{rw}}
CxA xA 0 {{cl}}
RtermA xA 0 1meg
D1A xA rAp {dmod}
D2A rBp xA {dmod}
RLAA rAp 0 500
CLAA rAp 0 0.2p
RLAB rBp 0 500
CLAB rBp 0 0.2p
BpA pwpA 0 V = V(drvA)*I(VsA)
* ---- pull (-1): -1mA at 40..~44n ----
IpB 0 dB PULSE(0 {{-ip}} 40n {{pw/5}} {{pw/5}} {{pw}} 200n)
VsB dB drvB DC 0
RwB drvB xB {{rw}}
CxB xB 0 {{cl}}
RtermB xB 0 1meg
D1B xB rAq {dmod}
D2B rBq xB {dmod}
RLBA rAq 0 500
CLBA rAq 0 0.2p
RLBB rBq 0 500
CLBB rBq 0 0.2p
BpB pwpB 0 V = V(drvB)*I(VsB)
* ---- push then pull back-to-back (charge recycling), 100n / 124n ----
Icy1 0 dC PULSE(0 {{ip}} 100n {{pw/5}} {{pw/5}} {{pw}} 200n)
Icy2 0 dC PULSE(0 {{-ip}} 124n {{pw/5}} {{pw/5}} {{pw}} 200n)
VsC dC drvC DC 0
RwC drvC xC {{rw}}
CxC xC 0 {{cl}}
RtermC xC 0 1meg
D1C xC rAc {dmod}
D2C rBc xC {dmod}
RLCA rAc 0 500
CLCA rAc 0 0.2p
RLCB rBc 0 500
CLCB rBc 0 0.2p
BpC pwpC 0 V = V(drvC)*I(VsC)
.ends
"""

def main():
    lines = []
    A = lines.append
    A("* =====================================================================")
    A("* ternary_sweep.cir  --  lever sweep of the AC-polarity ternary cell")
    A("* Generated by make_ternary_sweep.py (do not edit by hand).")
    A("* ")
    A("* Levers swept (full grid, 96 instances):")
    A("*   diode : DIDEAL (IS=1e-14) / DSCHOTTKY (IS=1e-9, Vf~0.35V)")
    A("*   IP    : 0.2m, 0.5m, 1m        pulse amplitude")
    A("*   PW    : 0.5n, 1n, 3n, 10n     pulse width (rise=fall=PW/5)")
    A("*   RW    : 100, 500              wire resistance")
    A("*   CLINE : 0.5p, 1p              wire capacitance")
    A("* ")
    A("* Each instance is a full 4-case cell (push / pull / push->pull cycle);")
    A("* energy = INTEG V(drv)*I(Vs) over the transfer window at the driver.")
    A("* Measure windows are fixed literals: any window tail after the pulse")
    A("* sees zero driver current, so it adds nothing to the integral.")
    A("* =====================================================================")
    A("")
    A(".options reltol=1e-3 abstol=1e-15 vntol=1e-6")
    A("")
    A("* ---------- diode models ----------")
    A(".model DIDEAL D (IS=1e-14 RS=50 CJO=0.2p TT=2n N=1.0)")
    A(".model DSCHOTTKY D (IS=1e-9 RS=50 CJO=0.2p TT=1n N=1.05)")
    A("")
    A("* ---------- parametrized cells (one per diode model) ----------")
    A(subckt("ternary_case", "DIDEAL"))
    A(subckt("ternary_case_s", "DSCHOTTKY"))
    A("* ---------- 96 sweep instances (model x IP x PW x RW x CLINE) ----------")
    for mod, sub, _ in MODS:
        for ip, ipv in IPS:
            for pw, pwv in PWS:
                for rw, rwv in RWS:
                    for cl, clv in CLS:
                        nm = f"X_{mod}_{ip}_{pw}_{rw}_{cl}"
                        A(f"{nm} vss {sub} ip={ipv} pw={pwv} rw={rwv} cl={clv}")
    A("")
    A("* ---------- global null case (idle driver, fixed) ----------")
    A("In 0 dN DC 0")
    A("RidleN dN 0 10meg")
    A("VsN dN drvN DC 0")
    A("RwN drvN xN 500")
    A("CxN xN 0 1p")
    A("RtermN xN 0 1meg")
    A("D1N xN rAn DIDEAL")
    A("D2N rBn xN DIDEAL")
    A("RLAN rAn 0 500")
    A("CLAN rAn 0 0.2p")
    A("RLBN rBn 0 500")
    A("CLBN rBn 0 0.2p")
    A("BpN pwpN 0 V = V(drvN)*I(VsN)")
    A("")
    A(".tran 100p 200n")
    A("")
    A("* ---------- measurements: 8 per instance ----------")
    for mod, _, _ in MODS:
        for ip, _ in IPS:
            for pw, _ in PWS:
                for rw, _ in RWS:
                    for cl, _ in CLS:
                        nm = f"X_{mod}_{ip}_{pw}_{rw}_{cl}"
                        A(f".meas tran epush_{nm} INTEG V({nm}.pwpA) {W_PUSH}")
                        A(f".meas tran epull_{nm} INTEG V({nm}.pwpB) {W_PULL}")
                        A(f".meas tran ecyc1_{nm} INTEG V({nm}.pwpC) {W_CYC1}")
                        A(f".meas tran ecyc2_{nm} INTEG V({nm}.pwpC) {W_CYC2}")
                        A(f".meas tran ecycT_{nm} INTEG V({nm}.pwpC) {W_CYCT}")
                        A(f".meas tran vraA_{nm} MAX V({nm}.rAp) {W_PUSH}")
                        A(f".meas tran vraB_{nm} MIN V({nm}.rBq) {W_PULL}")
                        A(f".meas tran vlnA_{nm} MAX V({nm}.drvA) {W_PUSH}")
    A(".meas tran enull INTEG V(pwpN) FROM=70n TO=90n")
    A(".meas tran vra_null MAX V(rAn) FROM=70n TO=90n")
    A(".meas tran vrb_null MIN V(rBn) FROM=70n TO=90n")
    A(".end")
    with open("ternary_sweep.cir", "w") as f:
        f.write("\n".join(lines) + "\n")

if __name__ == "__main__":
    main()
